FROM mysql:latest

# Set the root password for MySQL server
ENV MYSQL_ROOT_PASSWORD=password

# Create a new database and user
ENV MYSQL_DATABASE=mysql
ENV MYSQL_USER=mysql
ENV MYSQL_PASSWORD=mysql

# Copy the SQL script to create the database and user
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the default MySQL port
EXPOSE 3306

# Set the default command to start the MySQL server
CMD ["mysqld"]
